# Generated by Django 2.0.2 on 2018-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='song_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
