# Generated by Django 2.0.2 on 2018-05-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_feedback_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='mark',
        ),
    ]
